// src/pages/components/manifesto/index.tsx
import Taro from '@tarojs/taro'
import React from 'react'
import { View, Text } from '@tarojs/components'

import './index.scss'

const Manifesto = ({ text, participationId }: any) => {

  const linkToDetail = () => {
    Taro.navigateTo({ url: `/pages/articleDetail/index?id=${participationId}&type=Participation` })
  }

  return (
    <View className='manifesto-container' onClick={linkToDetail}>
      <Text>{text}</Text>
    </View>
  )
}

export default Manifesto

// src/pages/components/manifesto/index.vue
<template>
    <view class='manifesto-container' @tap="linkToDetail">
      <text>{{text}}</text>
    </view>
</template>

<script>
import Taro from '@tarojs/taro'
import './index.scss'
export default {
   props: {
       text: '',
       participationId: ''
   }, 
   methods: {
       linkToDetail() {
           Taro.navigateTo({ url: `/pages/articleDetail/index?id=${this.participationId}&type=Participation` })
       }
   }
}
</script>

<style>

</style>
